run:
  timeout: 5m
  modules-download-mode: readonly

linters:
  enable:
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - unused
    - gofmt
    - goimports
    - misspell
    - unconvert

  disable:
    - unparam      # Too many false positives for handlers
    - gosec        # Run separately with exclusions

linters-settings:
  errcheck:
    check-type-assertions: true
    check-blank: false
    # Ignore errors from these functions (common in HTTP handlers)
    exclude-functions:
      - (io.Writer).Write
      - (*encoding/json.Encoder).Encode
      - (*encoding/xml.Encoder).Encode
      - (net/http.ResponseWriter).Write
      - fmt.Fprint
      - fmt.Fprintf
      - fmt.Fprintln
      - fmt.Scanln
  
  govet:
    enable-all: true
    disable:
      - fieldalignment  # Too strict
      - shadow          # Too many false positives with err
  
  misspell:
    locale: US

issues:
  exclude-rules:
    # Ignore long lines in tests
    - path: _test\.go
      linters:
        - lll
    
    # Ignore errors in test files
    - path: _test\.go
      linters:
        - errcheck
    
    # Ignore unused params in test utilities
    - path: testutil/
      linters:
        - unparam

  max-issues-per-linter: 0
  max-same-issues: 0
